### ISSUE TITLE
Store Access is ignored

### ISSUE THREAD

**Issue by Cologler** [geeklearningio/gl-dotnet-storage#47]
file GeekLearning.Storage.FileSystem.Server/FileSystemStorageServerMiddleware
line 41.
`access != "Public"` always be true.

**Comment by sandorfr** [comment]
I think the bug is not that but the AND instead of a OR in the condition. I'll look into it.

**Comment by asiffermann** [comment]
This bug is fixed by #44 😃 
I'll keep it open until merge!
