### ISSUE TITLE
[feature request] impl GetExpirableUriAsync() for file system.

### ISSUE THREAD

**Issue by Cologler** [geeklearningio/gl-dotnet-storage#48]
e.g.

use `IMemoryCache` to cache uri and `IFileReference` with expired time. and detect it on `FileSystemStorageServerMiddleware`.

**Comment by sandorfr** [comment]
Hi, we plan to introduce a better api to support that and make it available on every provider. see https://github.com/geeklearningio/gl-dotnet-storage/issues/33 feel free to comment on this issue.
